-- Migración inicial: crea todas las tablas del sistema.
-- Referencia: Requerimientos v4, sección 11 (modelo de datos) y sección 4 (reglas de negocio).
--
-- Convenciones:
-- - Los id son "bigint GENERATED BY DEFAULT AS IDENTITY": la base asigna el número sola
--   (es la forma moderna de "serial").
-- - Los valores fijos (rol, estado, nivel, tipo) se validan con CHECK sobre texto, no con ENUM,
--   porque así se leen fácil y se cambian con una migración simple.
-- - Toda tabla guarda creado_en y modificado_en. Go actualiza modificado_en al editar.

-- +goose Up

-- Catálogo fijo de formas de vida. El id es el dígito del código del individuo (A-1-45-1).
CREATE TABLE formas_de_vida (
    id            smallint PRIMARY KEY CHECK (id BETWEEN 1 AND 4),
    nombre        text NOT NULL UNIQUE,
    icono         text NOT NULL, -- nombre del ícono de Material Symbols
    creado_en     timestamptz NOT NULL DEFAULT now(),
    modificado_en timestamptz NOT NULL DEFAULT now()
);

INSERT INTO formas_de_vida (id, nombre, icono) VALUES
    (1, 'Árbol',    'park'),
    (2, 'Arbusto',  'nature'),
    (3, 'Herbácea', 'local_florist'),
    (4, 'Rastrera', 'grass');

-- Institución adherida (universidad o colegio).
CREATE TABLE lugares (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    letra         text NOT NULL UNIQUE CHECK (letra ~ '^[A-Z]$'), -- RN-02: letra única
    nombre        text NOT NULL,
    tipo          text NOT NULL CHECK (tipo IN ('universidad', 'colegio')),
    localidad     text,
    latitud       numeric(9, 6),
    longitud      numeric(9, 6),
    es_publico    boolean NOT NULL DEFAULT false, -- RN-15
    activo        boolean NOT NULL DEFAULT true,
    creado_en     timestamptz NOT NULL DEFAULT now(),
    modificado_en timestamptz NOT NULL DEFAULT now()
);

-- Los usuarios no se borran: se deshabilitan (RN-13).
-- password_hash queda vacío mientras el usuario está "invitado" (todavía no definió su contraseña).
CREATE TABLE usuarios (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        text NOT NULL,
    email         text NOT NULL,
    password_hash text,
    rol           text NOT NULL CHECK (rol IN ('admin', 'cargador', 'lector')),
    estado        text NOT NULL DEFAULT 'invitado' CHECK (estado IN ('invitado', 'activo', 'deshabilitado')),
    lugar_id      bigint REFERENCES lugares (id),
    institucion   text, -- institución que pidió el acceso
    creado_en     timestamptz NOT NULL DEFAULT now(),
    modificado_en timestamptz NOT NULL DEFAULT now(),
    -- Un cargador siempre tiene un lugar asignado.
    CHECK (rol <> 'cargador' OR lugar_id IS NOT NULL)
);

-- Email único sin importar mayúsculas: "Ana@ucc.edu.ar" y "ana@ucc.edu.ar" son el mismo usuario.
CREATE UNIQUE INDEX usuarios_email_unico ON usuarios (lower(email));

-- RN-10: un lugar tiene como máximo un cargador activo.
-- Es un índice único "parcial": solo controla las filas que cumplen el WHERE.
CREATE UNIQUE INDEX usuarios_un_cargador_activo_por_lugar
    ON usuarios (lugar_id)
    WHERE rol = 'cargador' AND estado = 'activo';

-- Fotos subidas a Cloudflare R2. Se guarda la ruta dentro del bucket, nunca una URL pública:
-- las fotos se sirven por GET /api/fotos/{id}, que verifica permisos.
CREATE TABLE fotos (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ruta_r2    text NOT NULL UNIQUE,
    subida_por bigint NOT NULL REFERENCES usuarios (id),
    creado_en  timestamptz NOT NULL DEFAULT now()
);

-- Grupo de células dentro de un lugar, con su plano (foto de dron con una grilla).
CREATE TABLE isletas (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lugar_id      bigint NOT NULL REFERENCES lugares (id),
    numero        integer NOT NULL CHECK (numero >= 1),
    nombre        text,
    latitud       numeric(9, 6),
    longitud      numeric(9, 6),
    plano_foto_id bigint REFERENCES fotos (id),
    filas         integer NOT NULL CHECK (filas >= 1),
    columnas      integer NOT NULL CHECK (columnas >= 1),
    creado_en     timestamptz NOT NULL DEFAULT now(),
    modificado_en timestamptz NOT NULL DEFAULT now(),
    UNIQUE (lugar_id, numero) -- RN-02: número de isleta único por lugar
);

-- Célula de bosque: contenedor con 4 plantas.
-- Las células no se borran: se dan de baja con motivo y fecha.
CREATE TABLE celulas (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isleta_id        bigint NOT NULL REFERENCES isletas (id),
    numero           integer NOT NULL CHECK (numero >= 1),
    fila             integer NOT NULL CHECK (fila >= 1),
    columna          integer NOT NULL CHECK (columna >= 1),
    fecha_plantacion date NOT NULL,
    latitud          numeric(9, 6),
    longitud         numeric(9, 6),
    estado           text NOT NULL DEFAULT 'activa' CHECK (estado IN ('activa', 'baja')),
    motivo_baja      text,
    fecha_baja       date,
    creado_por       bigint NOT NULL REFERENCES usuarios (id),
    creado_en        timestamptz NOT NULL DEFAULT now(),
    modificado_por   bigint NOT NULL REFERENCES usuarios (id),
    modificado_en    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (isleta_id, numero),        -- RN-02: número de célula único por isleta
    UNIQUE (isleta_id, fila, columna), -- RN-02: una célula por posición del plano
    -- Si está dada de baja, tiene motivo y fecha; si está activa, no tiene ninguno de los dos.
    CHECK (
        (estado = 'activa' AND motivo_baja IS NULL AND fecha_baja IS NULL)
        OR (estado = 'baja' AND motivo_baja IS NOT NULL AND fecha_baja IS NOT NULL)
    )
);

-- Cada una de las 4 plantas de la célula (RN-01). Go las crea junto con la célula.
CREATE TABLE individuos (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    celula_id        bigint NOT NULL REFERENCES celulas (id),
    forma_de_vida_id smallint NOT NULL REFERENCES formas_de_vida (id),
    especie          text, -- opcional, a confirmar con la clienta
    creado_en        timestamptz NOT NULL DEFAULT now(),
    modificado_en    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (celula_id, forma_de_vida_id) -- un individuo por forma de vida por célula
);

-- Catálogo configurable de lo que se mide (RNF-MAN-02).
-- Si forma_de_vida_id es NULL, la variable aplica a las 4 formas de vida.
CREATE TABLE variables (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo           text NOT NULL UNIQUE,
    nombre           text NOT NULL,
    nivel            text NOT NULL CHECK (nivel IN ('registro', 'celula', 'individuo')),
    tipo             text NOT NULL CHECK (tipo IN ('entero', 'decimal', 'booleano', 'texto')),
    unidad           text,
    minimo           numeric,
    maximo           numeric,
    obligatoria      boolean NOT NULL DEFAULT false,
    forma_de_vida_id smallint REFERENCES formas_de_vida (id),
    orden            integer NOT NULL DEFAULT 0,
    activa           boolean NOT NULL DEFAULT true,
    creado_en        timestamptz NOT NULL DEFAULT now(),
    modificado_en    timestamptz NOT NULL DEFAULT now(),
    CHECK (minimo IS NULL OR maximo IS NULL OR minimo <= maximo)
);

-- Carga de una célula en un período. Los registros no se borran: se anulan con motivo (RN-12).
CREATE TABLE registros (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    celula_id        bigint NOT NULL REFERENCES celulas (id),
    fecha_medicion   date NOT NULL,
    -- Período = primer día del mes de la medición (2026-11-18 -> 2026-11-01).
    -- El CHECK garantiza que siempre sea día 1 y que coincida con la fecha de medición.
    periodo          date NOT NULL CHECK (periodo = date_trunc('month', fecha_medicion)::date),
    es_inicial       boolean NOT NULL DEFAULT false,
    foto_id          bigint NOT NULL REFERENCES fotos (id), -- RN-07: foto obligatoria
    observaciones    text CHECK (length(observaciones) <= 500),
    cobertura        numeric(4, 1) CHECK (cobertura BETWEEN 0 AND 100),
    fuera_de_termino boolean NOT NULL DEFAULT false,
    anulado          boolean NOT NULL DEFAULT false,
    motivo_anulacion text,
    creado_por       bigint NOT NULL REFERENCES usuarios (id),
    creado_en        timestamptz NOT NULL DEFAULT now(),
    modificado_por   bigint NOT NULL REFERENCES usuarios (id),
    modificado_en    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (celula_id, periodo), -- RN-04: un registro por célula por período
    CHECK (NOT anulado OR motivo_anulacion IS NOT NULL)
);

-- Un valor medido de una variable. individuo_id es NULL si la variable es del registro o de la célula.
-- Los booleanos (vivo, frutos, plántulas) se guardan como 1 (sí) o 0 (no) en valor_numerico.
CREATE TABLE mediciones (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro_id    bigint NOT NULL REFERENCES registros (id),
    variable_id    bigint NOT NULL REFERENCES variables (id),
    individuo_id   bigint REFERENCES individuos (id),
    valor_numerico numeric,
    valor_texto    text,
    creado_en      timestamptz NOT NULL DEFAULT now(),
    modificado_en  timestamptz NOT NULL DEFAULT now(),
    -- No se mide dos veces lo mismo en un registro.
    -- NULLS NOT DISTINCT hace que dos NULL en individuo_id cuenten como iguales.
    UNIQUE NULLS NOT DISTINCT (registro_id, variable_id, individuo_id),
    CHECK (valor_numerico IS NOT NULL OR valor_texto IS NOT NULL)
);

-- Sesiones abiertas. El token viaja en una cookie HttpOnly.
CREATE TABLE sesiones (
    token      text PRIMARY KEY,
    usuario_id bigint NOT NULL REFERENCES usuarios (id),
    expira_en  timestamptz NOT NULL,
    creado_en  timestamptz NOT NULL DEFAULT now()
);

-- Auditoría: una fila por cada campo modificado (AUD-02).
CREATE TABLE cambios (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entidad        text NOT NULL, -- nombre de la tabla, por ejemplo 'registros'
    entidad_id     bigint NOT NULL,
    campo          text NOT NULL,
    valor_anterior text,
    valor_nuevo    text,
    usuario_id     bigint NOT NULL REFERENCES usuarios (id),
    creado_en      timestamptz NOT NULL DEFAULT now()
);

-- +goose Down
-- Se borran en orden inverso para no romper las claves foráneas.
DROP TABLE cambios;
DROP TABLE sesiones;
DROP TABLE mediciones;
DROP TABLE registros;
DROP TABLE variables;
DROP TABLE individuos;
DROP TABLE celulas;
DROP TABLE isletas;
DROP TABLE fotos;
DROP TABLE usuarios;
DROP TABLE lugares;
DROP TABLE formas_de_vida;
